name = "HistoricalStdlibVersions"
uuid = "6df8b67a-e8a0-4029-b4b7-ac196fe72102"
authors = ["Ian <i.r.butterworth@gmail.com>"]
version = "2.0.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
